---
abstract: 'Simple parallel ssh client.'
author:
  - 'Brian Duggan <brian.duggan@nasa.gov>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4002, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Clustericious-Admin
provides:
  Clustericious::Admin:
    file: lib/Clustericious/Admin.pm
    version: 0.21
requires:
  Clustericious::Config: 0
  Clustericious::Log: 0
  Hash::Merge: 0
  Log::Log4perl::CommandLine: 0
  Mojolicious: 2.69
  Term::ANSIColor: 0
  Test::More: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.21
